export const websiteNiches = [
  { value: "", label: "Select Website Niche/Category" },
  { value: "Technology", label: "Technology" },
  { value: "Health & Fitness", label: "Health & Fitness" },
  { value: "Finance", label: "Finance" },
  { value: "Business", label: "Business" },
  { value: "Marketing", label: "Marketing" },
  { value: "SEO", label: "SEO" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Content Marketing", label: "Content Marketing" },
  { value: "Social Media", label: "Social Media" },
  { value: "Web Design", label: "Web Design" },
  { value: "Education", label: "Education" },
  { value: "Travel", label: "Travel" },
  { value: "Food & Cooking", label: "Food & Cooking" },
  { value: "Lifestyle", label: "Lifestyle" },
  { value: "Fashion", label: "Fashion" },
  { value: "Beauty", label: "Beauty" },
  { value: "Sports", label: "Sports" },
  { value: "Entertainment", label: "Entertainment" },
  { value: "News", label: "News" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Automotive", label: "Automotive" },
  { value: "Home & Garden", label: "Home & Garden" },
  { value: "Parenting", label: "Parenting" },
  { value: "Pets", label: "Pets" },
  { value: "Gaming", label: "Gaming" },
  { value: "Photography", label: "Photography" },
  { value: "Art & Design", label: "Art & Design" },
  { value: "Music", label: "Music" },
  { value: "Books & Literature", label: "Books & Literature" },
  { value: "Science", label: "Science" },
  { value: "Environment", label: "Environment" },
  { value: "Politics", label: "Politics" },
  { value: "Law", label: "Law" },
  { value: "Medical", label: "Medical" },
  { value: "Psychology", label: "Psychology" },
  { value: "Religion", label: "Religion" },
  { value: "Other", label: "Other" },
];
